### ISSUE TITLE
throws error if titlepage is missing

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/quarto_titlepages#22]
```
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside"]
    toc: true
    toc-depth: 2
    lof: true
    lot: true
```

Error running filter _extensions/nmfs-opensci/titlepage/titlepage-theme.lua:
PandocLuaError "Cannot get Attr from TypeNil"
stack traceback:
	_extensions/nmfs-opensci/titlepage/titlepage-theme.lua:11: in upvalue 'getVal'
	_extensions/nmfs-opensci/titlepage/titlepage-theme.lua:389: in function 'Meta'
