### ISSUE TITLE
colorbox-fill not working

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/quarto_titlepages#23]
Always cyan
```
    titlepage-theme:
      page-html-color: "4191cc"
      title-style: "colorbox"
      colorbox-fill: "red"
```
