### ISSUE TITLE
`title-fontsize` is having no effect on the title font size when rendering to pdf format

### ISSUE THREAD

**Issue by shafayetShafee** [nmfs-opensci/quarto_titlepages#35]
### Bug Description and steps to reproduce

If we try the following reprex,

~~~
---
title: "Test page tilte font size"
date: last-modified  
format:  
  titlepage-pdf:  
    documentclass: scrbook
    titlepage: plain  
    titlepage-theme:
      title-fontsize: 50
      title-align: center
keep-tex: true
---
~~~

we get the following output,

---
![image](https://user-images.githubusercontent.com/48413872/218004138-ed6f735e-3ff1-4670-96bc-01401debb6b9.png)
---

And clearly, the title font size is not as expected. After checking the intermediate tex file I see that,

~~~
\newcommand{\titleandsubtitle}{
% Title and subtitle
{\fontsize{50}{60.0}\selectfont
{\Large{\nohyphens{Test page tilte font size}}}\par
}%
}
~~~

And it seems font size 50 is getting overridden by `\Large`. So no matter what value is assigned to `title-fontsize`, none of them will work.

*Note that, this issue mainly originates from [this Stackoverflow question](https://stackoverflow.com/questions/75379268/change-title-size-with-quarto-titlepages-extension-when-rendering-to-pdf) where a working solution is provided*

### Version and Sytem info

- **Quarto Version:** I have faced this behaviour in both quarto version *1.1.251* and *1.3.151* while running from Rstudio.
- **TeX version:** TeX 3.14159265 (TeX Live 2019/Debian)
- **OS info**: Ubuntu 20.04.5 LTS

**Comment by eeholmes** [comment]
Yes, it is a rather confusing problem that I wasn't sure how to solve. The `title-fontsize` is being overridden by `title-style`.  You need to set `title-fontstyle: []` This will work:

```
---
title: "Test page tilte font size"
date: last-modified  
format:  
  titlepage-pdf:  
    documentclass: scrbook
    titlepage: plain  
    titlepage-theme:
      title-fontsize: 50
      title-align: center
      title-fontstyle: []
keep-tex: true
---
```

I considered doing a check if `title-fontsize` is spec-ed and then check if any fontsize is being set in `title-fontstyle` and disallow that. But I haven't coded that. I am thinking perhaps to just 'outlaw' any fontsize in `title-fontstyle` and require `title-fontsize` for that. The only problem is that you also need to set `title-fontspacing`; there is a default, but it doesn't always look good. Maybe I should just issue a warning if `title-fontsize` is set and `title-fontstyle` has a font size spec.
