### ISSUE TITLE
New line/break in coverpage blocks

### ISSUE THREAD

**Issue by leonhead-acer** [nmfs-opensci/quarto_titlepages#48]
Hello

I've been trying to introduce a new line/line break into the coverpage fields, but nothing seems to work. I've tried all of the options listed here:
https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines?rq=2

Any advice on this would be much appreciated :)

**Comment by eeholmes** [comment]
This?

<img width="285" alt="image" src="https://github.com/nmfs-opensci/quarto_titlepages/assets/2545978/83dd2627-81a7-41ec-8c81-4e2356033a00">

```
    coverpage-title: |
      Otters\
      Are Cute\
```

**Comment by eeholmes** [comment]
Did you see the "great wave" example where I use the footer element to create a subtitle?

https://nmfs-opensci.github.io/quarto_titlepages/05-coverpage-themes.html#great-wave-1

```
    coverpage-title: |
      Otters\
      Are Cute\
    coverpage-footer: |
      and sea otters\
      are even cuter!\
    coverpage-theme:
      title-color: "white"
      title-fontfamily: "QTDublinIrish.otf"
      title-fontsize: 100
      author-style: "plain"
      author-sep: "newline"
      author-fontstyle: "textsc"
      author-fontsize: 30
      author-align: "right"
      author-bottom: "2in"
      header-style: "none"
      date-style: "none"
      footer-style: "plain"
      footer-color: "white"
      footer-fontsize: 20
      footer-fontfamily: "QTDublinIrish.otf"
      footer-align: "right"
      footer-bottom: "6.5in"
      keep-tex: true
```

**Comment by eeholmes** [comment]
Result is this

<img width="875" alt="image" src="https://github.com/nmfs-opensci/quarto_titlepages/assets/2545978/404537b4-dbaa-4955-b6dc-ef1b70a31c81">

**Comment by leeroyaus** [comment]
(Sorry, `leeroyaus` is my other github account)

**Comment by eeholmes** [comment]
works with `coverpage: great-wave` also

**Comment by eeholmes** [comment]
Here is a repo of a Quarto book using the titlepages-pdf format. This works for me.

https://github.com/eeholmes/test_quarto-titlepages

**Comment by leeroyaus** [comment]
> Here is my full format spec
> 
> ```
> format: 
>   titlepage-pdf:
>     documentclass: scrbook
>     classoption: ["oneside", "open=any"]
>     number-sections: true
>     toc: true
>     lof: true
>     lot: true
>     titlepage: "bg-image"
>     titlepage-theme:
>       elements: ["\\titleblock", "\\authorblock", "\\vfill", "\\dateblock", "\\affiliationblock",  "\\logoblock", "\\footerblock"]
>     titlepage-bg-image: "img/corner-bg.png"
>     titlepage-logo: "img/logo.png"
>     titlepage-header: "The Publisher"
>     titlepage-footer: |
>       NOAA Fisheries OpenSci\
>       Tools for Open Science\
>       [https://github.com/nmfs-opensci](https://github.com/nmfs-opensci)\
>     coverpage-include-file:
>       - tex/copyright.tex
>     titlepage-include-file:
>       - tex/dedication.tex
>     coverpage: true
>     coverpage-bg-image: "img/otter-bar.jpeg"
>     coverpage-title: |
>       Otters\
>       Are Cute\
>     coverpage-footer: |
>       and sea otters\
>       are even cuter!\
>     coverpage-author: ["EE", "Holmes"]
>     coverpage-theme:
>       title-color: "white"
>       title-fontfamily: "QTDublinIrish.otf"
>       title-fontsize: 100
>       author-style: "plain"
>       author-sep: "newline"
>       author-fontstyle: "textsc"
>       author-fontsize: 30
>       author-align: "right"
>       author-bottom: "2in"
>       header-style: "none"
>       date-style: "none"
>       footer-style: "plain"
>       footer-color: "white"
>       footer-fontsize: 20
>       footer-fontfamily: "QTDublinIrish.otf"
>       footer-align: "right"
>       footer-bottom: "6.5in"
>       keep-tex: true
> ```

In my cover page there will just be title and footer (with footer technically a subtitle). When I try to remove the author field from the coverpage I get the same error as before. Is this expected?

**Comment by eeholmes** [comment]
Hmm, that's a bug. But you can easily remove the author. Use
```
author-style: "none"
```
in the `coverpage-theme` section of the yaml.

**Comment by leeroyaus** [comment]
Actually no, the author is still appearing - it was just black font on a black background. Here's a zoomed in image:
![image](https://github.com/nmfs-opensci/quarto_titlepages/assets/64235329/350f75c2-58f8-43b3-8501-076ba0aea9c6)

````
format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: true
    toc: true
    lof: true
    lot: true
    titlepage: "bg-image"
    titlepage-theme:
      elements: ["\\titleblock", "\\authorblock", "\\vfill", "\\dateblock", "\\affiliationblock",  "\\logoblock", "\\footerblock"]
    titlepage-bg-image: "img/corner-bg.png"
    titlepage-logo: "img/logo.png"
    titlepage-header: "The Publisher"
    titlepage-footer: |
      NOAA Fisheries OpenSci\
      Tools for Open Science\
      [https://github.com/nmfs-opensci](https://github.com/nmfs-opensci)\
    coverpage-include-file:
      - tex/copyright.tex
    titlepage-include-file:
      - tex/dedication.tex
    coverpage: true
    coverpage-bg-image: "img/otter-bar.jpeg"
    coverpage-title: |
      Otters\
      Are Cute\
    coverpage-footer: |
      and sea otters\
      are even cuter!\
    coverpage-author: ["EE", "Holmes"]
    coverpage-theme:
      title-color: "white"
      title-fontfamily: "QTDublinIrish.otf"
      title-fontsize: 100
      author-style: "none"
      header-style: "none"
      date-style: "none"
      footer-style: "plain"
      footer-color: "white"
      footer-fontsize: 20
      footer-fontfamily: "QTDublinIrish.otf"
      footer-align: "right"
      footer-bottom: "6.5in"
      keep-tex: true

````
