### ISSUE TITLE
coverpage-theme lua error when no author

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/quarto_titlepages#50]
When no author, you get this error even if `author-style: "none"`

```
Error running filter /Applications/quarto/share/filters/main.lua:
...t/_extensions/nmfs-opensci/titlepage/coverpage-theme.lua:271: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        ...t/_extensions/nmfs-opensci/titlepage/coverpage-theme.lua:271: in function <...t/_extensions/nmfs-opensci/titlepage/coverpage-theme.lua:47>
```

Here is my yaml. Make sure to remove the author from the top yaml.
```
format: 
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    number-sections: true
    toc: true
    lof: true
    lot: true
    titlepage: "bg-image"
    titlepage-theme:
      elements: ["\\titleblock", "\\authorblock", "\\vfill", "\\dateblock", "\\affiliationblock",  "\\logoblock", "\\footerblock"]
    titlepage-bg-image: "img/corner-bg.png"
    titlepage-logo: "img/logo.png"
    titlepage-header: "The Publisher"
    titlepage-footer: |
      NOAA Fisheries OpenSci\
      Tools for Open Science\
      [https://github.com/nmfs-opensci](https://github.com/nmfs-opensci)\
    coverpage-include-file:
      - tex/copyright.tex
    titlepage-include-file:
      - tex/dedication.tex
    coverpage: true
    coverpage-bg-image: "img/otter-bar.jpeg"
    coverpage-title: |
      Otters\
      Are Cute\
    coverpage-footer: |
      and sea otters\
      are even cuter!\
    coverpage-theme:
      title-color: "white"
      title-fontfamily: "QTDublinIrish.otf"
      title-fontsize: 100
      author-style: "none"
      author-sep: "newline"
      author-fontstyle: "textsc"
      author-fontsize: 30
      author-align: "right"
      author-bottom: "2in"
      header-style: "none"
      date-style: "none"
      footer-style: "plain"
      footer-color: "white"
      footer-fontsize: 20
      footer-fontfamily: "QTDublinIrish.otf"
      footer-align: "right"
      footer-bottom: "6.5in"
      keep-tex: true
```
