### ISSUE TITLE
vrule-color does not work

### ISSUE THREAD

**Issue by Michael-Sheppard** [nmfs-opensci/quarto_titlepages#55]
* Quarto version: v1.4.554
* OS: Windows
* Render method: Desktop RStudio, rendering to PDF
* TeX version: MiKTeX-TeX 4.6 (MiKTeX 24.3.31)

### Description

According to titlepage-theme options listed on https://nmfs-opensci.github.io/quarto_titlepages/02-titlepages.html, users should have the ability to change the color of the vertical rule on the title page by specifying vrule-color under titlepage-theme. I am able to successfully change the title font color using title-color, but using vrule-color does nothing or seems to be ignored. 

### Steps to Reproduce

To reproduce what I am doing, I simply used example_1.qmd that comes with installation of the extension. Under titlepage-pdf, I added the following right below line 44 `keep-tex: TRUE`

```
    titlepage-theme:
      elements: ["\\titleblock", "\\logoblock", "\\authorblock", "\\vfill", "\\footerblock", "\\affiliationblock"]
      title-color: "myblue"
      vrule-color: "mygreen"
      vrule-width: "3pt"
    include-in-header:
      text: |
        \definecolor{myblue}{HTML}{1C4980}
        \definecolor{mygreen}{HTML}{808000}
```
Yet, the vertical rule continues to render in black. 
![image](https://github.com/nmfs-opensci/quarto_titlepages/assets/60410363/72f7cae9-5a37-4675-9db9-029c6ef5c795)
