### ISSUE TITLE
title page background image opacity not working

### ISSUE THREAD

**Issue by espinielli** [nmfs-opensci/quarto_titlepages#62]
### Description

My understanding of the documentation for [All possible `titlepage-theme` values](https://nmfs-opensci.github.io/quarto_titlepages/02-titlepages.html#all-possible-titlepage-theme-values) is that you can set the background image opacity.
In the example below my settings for opacity are not enacted...I checked the code and it also seems to me that `wallpaper.sty` which is used for the background image, does not really (unfortunately) support that.

Here is the content of `_quarto.yml`:

```yaml
project:
  type: book

book:
  title: A Sample Title
  author:
    - name: Jane Doe
  chapters:
    - index.qmd
  output-file: book

format: 
  titlepage-pdf:
    keep-tex: true
    coverpage: false
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "formal"
    titlepage-bg-image: "sceau-a-quadri.png"
    titlepage-theme:
      bg-image-size: "0.25\\paperwidth"
      bg-image-location: "Center"
      bg-image-fading: "top"
      bg-image-opacity: 0.1
      keep-tex: true
```

My final aim is about being able to positioning at discretion a background image with opacity in the title page.
The `wallpaper.sty` manual mentions the possibility of offestting from ULCorner/.../Center via `\wpXoffset` or `\wpYoffset` but i haven't been able to getting it done...

### Steps to Reproduce

See repo, for reproducibility: 
   <https://github.com/espinielli/bug_quarto-titlepages>
Simply `quarto render`
I attached the rendered PDF [book.pdf](https://github.com/user-attachments/files/20242397/book.pdf)

### Setup
* `quarto --version`: 1.7.30 
* operating system (`sw_ver` command):
   > ProductName:            macOS
   > ProductVersion:         15.4.1
   > BuildVersion:           24E263
* the bug relate to PDF output
* I am rendering Quarto docs via RStudio
* TeX version (`tex --version` command output):
   > TeX 3.141592653 (TeX Live 2025)
   > kpathsea version 6.4.1
   > Copyright 2025 D.E. Knuth.
   > There is NO warranty.  Redistribution of this software is
   > covered by the terms of both the TeX copyright and
   > the Lesser GNU General Public License.
   > For more information about these matters, see the file
   > named COPYING and the TeX source.
   > Primary author of TeX: D.E. Knuth.
